name: Markdown Links Validation
on: [push, workflow_dispatch]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout this repository
      uses: actions/checkout@master

    - name: Download .markdownlint.json
      uses: fharper/wget@v1
      with:
        args: https://raw.githubusercontent.com/fharper/gh-configs/main/.markdownlinkcheck.json

    - name: Validate Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.markdownlinkcheck.json'
