name: Markdown Syntax Validation
on: push

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@main

      - name: Validate Markdown
        uses: DavidAnson/markdownlint-cli2-action@v9.0.0
        with:
            command: config
            globs: |
              .markdownlint.json
              **.md
